import { describe, it } from "node:test";
import { getUsageEntriesFromDay } from "./parse-ek-data.js";
import assert from "node:assert";
import { Temporal } from "temporal-polyfill";
import { pp } from "../../plans/utils.js";

describe("getUsageEntriesFromDay", () => {
  const day = "2024-06-01";
  it("should calculate usage correctly", () => {
    const usageEntries = getUsageEntriesFromDay(day, getSampleDailyUsage());
    assert.deepStrictEqual(usageEntries[5], {
      startDate: Temporal.ZonedDateTime.from(
        day + "T05:00:00[Pacific/Auckland]"
      ),
      usage: 0.18,
    });
    assert.deepStrictEqual(usageEntries[11], {
      startDate: Temporal.ZonedDateTime.from(
        day + "T11:00:00[Pacific/Auckland]"
      ),
      usage: 0.19,
    });
    const total = usageEntries.reduce((acc, curr) => acc + curr.usage, 0);
    assert.strictEqual(total.toFixed(2), "7.81");
    console.log(pp(usageEntries));
  });
});

/**
 * Returns daily usage data from 2024-06-01
 */
function getSampleDailyUsage() {
  return {
    adjustment_charges_incl_gst: "0.28",
    bill_consumption: "6.56",
    consumption: "7.81",
    consumption_adjustment: "1.25",
    feed_in_tariffs: {},
    fixed_charges_excl_gst: "2.19",
    fixed_charges_incl_gst: "2.52",
    flat: {},
    intervals: {
      1: {
        consumption: "0.10",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "12:00 AM",
      },
      10: {
        consumption: "0.10",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "4:30 AM",
      },
      11: {
        consumption: "0.09",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "5:00 AM",
      },
      12: {
        consumption: "0.09",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "5:30 AM",
      },
      13: {
        consumption: "0.09",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "6:00 AM",
      },
      14: {
        consumption: "0.09",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "6:30 AM",
      },
      15: {
        consumption: "0.40",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "7:00 AM",
      },
      16: {
        consumption: "0.27",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "7:30 AM",
      },
      17: {
        consumption: "0.29",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "8:00 AM",
      },
      18: {
        consumption: "0.23",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "8:30 AM",
      },
      19: {
        consumption: "0.98",
        consumption_rate: 0.2257,
        hop_best: 1,
        hop_interval: 1,
        time: "9:00 AM",
      },
      2: {
        consumption: "0.08",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "12:30 AM",
      },
      20: {
        consumption: "0.27",
        consumption_rate: 0.2257,
        hop_best: 1,
        hop_interval: 1,
        time: "9:30 AM",
      },
      21: {
        consumption: "0.08",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "10:00 AM",
      },
      22: {
        consumption: "0.10",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "10:30 AM",
      },
      23: {
        consumption: "0.10",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "11:00 AM",
      },
      24: {
        consumption: "0.09",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "11:30 AM",
      },
      25: {
        consumption: "0.09",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "12:00 PM",
      },
      26: {
        consumption: "0.10",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "12:30 PM",
      },
      27: {
        consumption: "0.10",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "1:00 PM",
      },
      28: {
        consumption: "0.08",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "1:30 PM",
      },
      29: {
        consumption: "0.10",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "2:00 PM",
      },
      3: {
        consumption: "0.10",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "1:00 AM",
      },
      30: {
        consumption: "0.10",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "2:30 PM",
      },
      31: {
        consumption: "0.09",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "3:00 PM",
      },
      32: {
        consumption: "0.09",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "3:30 PM",
      },
      33: {
        consumption: "0.10",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "4:00 PM",
      },
      34: {
        consumption: "0.10",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "4:30 PM",
      },
      35: {
        consumption: "0.09",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "5:00 PM",
      },
      36: {
        consumption: "0.09",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "5:30 PM",
      },
      37: {
        consumption: "0.10",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "6:00 PM",
      },
      38: {
        consumption: "0.09",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "6:30 PM",
      },
      39: {
        consumption: "0.41",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "7:00 PM",
      },
      4: {
        consumption: "0.10",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "1:30 AM",
      },
      40: {
        consumption: "0.22",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "7:30 PM",
      },
      41: {
        consumption: "0.29",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "8:00 PM",
      },
      42: {
        consumption: "0.24",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "8:30 PM",
      },
      43: {
        consumption: "0.19",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "9:00 PM",
      },
      44: {
        consumption: "0.31",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "9:30 PM",
      },
      45: {
        consumption: "0.30",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "10:00 PM",
      },
      46: {
        consumption: "0.23",
        consumption_rate: 0.2257,
        hop_best: 0,
        hop_interval: 0,
        time: "10:30 PM",
      },
      47: {
        consumption: "0.10",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "11:00 PM",
      },
      48: {
        consumption: "0.09",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "11:30 PM",
      },
      5: {
        consumption: "0.09",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "2:00 AM",
      },
      6: {
        consumption: "0.09",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "2:30 AM",
      },
      7: {
        consumption: "0.10",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "3:00 AM",
      },
      8: {
        consumption: "0.09",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "3:30 AM",
      },
      9: {
        consumption: "0.09",
        consumption_rate: 0.1612,
        hop_best: 0,
        hop_interval: 0,
        time: "4:00 AM",
      },
    },
    percent_consumption_adjustment: "16.0",
    range: { end_date: "2024-06-01", start_date: "2024-06-01" },
    solar_feed_in_tariffs: 0,
    status: "B",
    total_charges_incl_gst: "3.90",
    tou: {},
    tou_plus: {
      highest_off_peak_interval: "1",
      interval_types: ["off_peak_night", "off_peak_shoulder"],
      off_peak_night: {
        color_code: "#DOEDCB",
        consumption: "1.49",
        intervals: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "47",
          "48",
          "49",
          "50",
        ],
        percentage: "19.08",
        variable_charges_excl_gst: "0.21",
        variable_charges_incl_gst: "0.24",
      },
      off_peak_shoulder: {
        color_code: "#A1DC97",
        consumption: "6.32",
        intervals: [
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
          "41",
          "42",
          "43",
          "44",
          "45",
          "46",
        ],
        percentage: "80.92",
        variable_charges_excl_gst: "1.00",
        variable_charges_incl_gst: "1.14",
      },
    },
    type: "A",
    usage_type: "tou_plus",
  };
}
